#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")" && pwd)"
SECONDS_TO_RUN="${1:-0}"
TRIGGER_HZ="${2:-30}"
ARCH="$(uname -m)"

if [[ "${FORCE_NON_ARM:-0}" != "1" && "$ARCH" != "aarch64" ]]; then
  echo "[ERR] This project must run on ARM64 Jetson (current: $ARCH)."
  echo "[ERR] Run it on Jetson. To bypass: FORCE_NON_ARM=1 ./run.sh $SECONDS_TO_RUN $TRIGGER_HZ"
  exit 1
fi

if [[ -z "${DISPLAY:-}" && -n "${PULSAR_DISPLAY:-}" ]]; then
  export DISPLAY="$PULSAR_DISPLAY"
elif [[ -z "${DISPLAY:-}" ]]; then
  export DISPLAY=:0
fi

cd "$ROOT_DIR/pulsar"
make -j"$(nproc)"

export LD_LIBRARY_PATH="$ROOT_DIR/Galaxy_camera/lib/armv8:${LD_LIBRARY_PATH:-}"
export PULSAR_FAKE_PROFILE="${PULSAR_FAKE_PROFILE:-0}"
export PULSAR_PROFILE_EXPOSURE_US="${PULSAR_PROFILE_EXPOSURE_US:-34000}"
export PULSAR_EXPOSURE_US="${PULSAR_EXPOSURE_US:-34000}"
export PULSAR_GAIN="${PULSAR_GAIN:-10}"
export PULSAR_GAMMA="${PULSAR_GAMMA:-0.75}"
export PULSAR_BLACK_LEVEL="${PULSAR_BLACK_LEVEL:-1}"
export PULSAR_BALANCE_RATIO="${PULSAR_BALANCE_RATIO:-2}"
export PULSAR_LIGHT_SOURCE_PRESET="${PULSAR_LIGHT_SOURCE_PRESET:-3}"
export PULSAR_SWAP_RB="${PULSAR_SWAP_RB:-1,1}"
export PULSAR_TRIGGER_MODE="${PULSAR_TRIGGER_MODE:-continuous}"
export PULSAR_SYNC_TO_SLOWEST="${PULSAR_SYNC_TO_SLOWEST:-0}"
export PULSAR_ADAPTIVE_LOOP="${PULSAR_ADAPTIVE_LOOP:-0}"
export PULSAR_DISPLAY_REQUIRE_PAIR="${PULSAR_DISPLAY_REQUIRE_PAIR:-0}"
export PULSAR_ACQ_BUFFER_NUM="${PULSAR_ACQ_BUFFER_NUM:-8}"
export PULSAR_FETCH_TIMEOUT_MS="${PULSAR_FETCH_TIMEOUT_MS:-50}"
export PULSAR_OPENCV_THREADS="${PULSAR_OPENCV_THREADS:-1}"
export PULSAR_STALE_WARN_MS="${PULSAR_STALE_WARN_MS:-120}"
exec ./pulsar_rt "$SECONDS_TO_RUN" "$TRIGGER_HZ"
