log4cplus.rootLogger=ERROR, FILE
log4cplus.appender.FILE=log4cplus::RollingFileAppender
<<<<<<< HEAD
log4cplus.appender.FILE.File=/home/amin/Documents/Pulsar-3d-main/.runtime/logs/sdk.log
=======
log4cplus.appender.FILE.File=/home/amin/Pictures/pulsar-3d/.runtime/logs/sdk.log
>>>>>>> 23880dfe18a93e4ea0713b6e9b2044fb2ba55403
log4cplus.appender.FILE.CreateDirs=true
log4cplus.appender.FILE.MaxFileSize=20MB
log4cplus.appender.FILE.MaxBackupIndex=2
log4cplus.appender.FILE.layout=log4cplus::PatternLayout
log4cplus.appender.FILE.layout.ConversionPattern=%D{%Y-%m-%d %H:%M:%S:%q};%p;%t;%c;[%l];%m%n
